apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: todo-app
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: todo-app
spec:
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: ClusterIP
